import type { EtsyListing } from "./etsy-client";
import type { AIRecommendations } from "./ai-suggestions";
import type { KeywordResearchResult } from "./keyword-research";

export const DEMO_MODE = process.env.NEXT_PUBLIC_DEMO_MODE === "true";

// --- Mock Listings ---

export const MOCK_LISTINGS: EtsyListing[] = [
  {
    listing_id: 1001,
    title: "Handmade Ceramic Vase | Modern Home Decor | Minimalist Pottery | Flower Vase for Living Room",
    description: "Beautiful handmade ceramic vase crafted with care. Perfect for modern home decor.\n\nThis minimalist pottery piece adds elegance to any room. Each vase is unique and made by hand.\n\nDimensions:\n- Height: 8 inches\n- Width: 4 inches\n- Opening: 2.5 inches\n\nMaterials: High-fire stoneware clay with a matte glaze finish.\n\nCare instructions: Hand wash only. Not microwave safe.\n\nShipping: Ships within 3-5 business days. Carefully packaged to prevent damage.",
    tags: [
      "ceramic vase", "handmade pottery", "modern home decor", "minimalist vase",
      "flower vase", "living room decor", "housewarming gift", "stoneware vase",
      "matte vase", "boho home decor", "pottery vase", "decorative vase", "unique vase"
    ],
    price: { amount: 4500, divisor: 100, currency_code: "USD" },
    quantity: 12,
    taxonomy_id: 6648,
    materials: ["stoneware clay", "matte glaze"],
    shipping_profile_id: 101,
    processing_min: 3,
    processing_max: 5,
    who_made: "i_did",
    when_made: "2020_2025",
    styles: ["Minimalist", "Modern"],
    is_personalizable: false,
    personalization_char_count_max: 0,
    personalization_instructions: "",
    views: 1247,
    state: "active",
    url: "https://www.etsy.com/listing/1001/handmade-ceramic-vase",
    shop_section_id: 201,
    images: [
      { listing_image_id: 5001, listing_id: 1001, url_75x75: "https://placehold.co/75/1a1a1a/888?text=Vase", url_170x135: "https://placehold.co/170x135/1a1a1a/888?text=Vase", url_570xN: "https://placehold.co/570x456/1a1a1a/888?text=Ceramic+Vase", url_fullxfull: "https://placehold.co/1200/1a1a1a/888?text=Ceramic+Vase", alt_text: "Handmade ceramic vase with matte finish for modern home decor", rank: 1 },
      { listing_image_id: 5002, listing_id: 1001, url_75x75: "https://placehold.co/75/1a1a1a/888?text=V2", url_170x135: "https://placehold.co/170x135/1a1a1a/888?text=V2", url_570xN: "https://placehold.co/570x456/1a1a1a/888?text=Side+View", url_fullxfull: "https://placehold.co/1200/1a1a1a/888?text=Side+View", alt_text: "Minimalist pottery vase side view showing texture", rank: 2 },
      { listing_image_id: 5003, listing_id: 1001, url_75x75: "https://placehold.co/75/1a1a1a/888?text=V3", url_170x135: "https://placehold.co/170x135/1a1a1a/888?text=V3", url_570xN: "https://placehold.co/570x456/1a1a1a/888?text=Top+View", url_fullxfull: "https://placehold.co/1200/1a1a1a/888?text=Top+View", alt_text: "", rank: 3 },
      { listing_image_id: 5004, listing_id: 1001, url_75x75: "https://placehold.co/75/1a1a1a/888?text=V4", url_170x135: "https://placehold.co/170x135/1a1a1a/888?text=V4", url_570xN: "https://placehold.co/570x456/1a1a1a/888?text=With+Flowers", url_fullxfull: "https://placehold.co/1200/1a1a1a/888?text=With+Flowers", alt_text: "Vase with fresh flowers in a living room setting", rank: 4 },
      { listing_image_id: 5005, listing_id: 1001, url_75x75: "https://placehold.co/75/1a1a1a/888?text=V5", url_170x135: "https://placehold.co/170x135/1a1a1a/888?text=V5", url_570xN: "https://placehold.co/570x456/1a1a1a/888?text=Detail", url_fullxfull: "https://placehold.co/1200/1a1a1a/888?text=Detail", alt_text: "Close-up of handmade stoneware texture", rank: 5 },
      { listing_image_id: 5006, listing_id: 1001, url_75x75: "https://placehold.co/75/1a1a1a/888?text=V6", url_170x135: "https://placehold.co/170x135/1a1a1a/888?text=V6", url_570xN: "https://placehold.co/570x456/1a1a1a/888?text=Scale", url_fullxfull: "https://placehold.co/1200/1a1a1a/888?text=Scale", alt_text: "", rank: 6 },
      { listing_image_id: 5007, listing_id: 1001, url_75x75: "https://placehold.co/75/1a1a1a/888?text=V7", url_170x135: "https://placehold.co/170x135/1a1a1a/888?text=V7", url_570xN: "https://placehold.co/570x456/1a1a1a/888?text=Packaging", url_fullxfull: "https://placehold.co/1200/1a1a1a/888?text=Packaging", alt_text: "Eco-friendly packaging for safe shipping", rank: 7 },
      { listing_image_id: 5008, listing_id: 1001, url_75x75: "https://placehold.co/75/1a1a1a/888?text=V8", url_170x135: "https://placehold.co/170x135/1a1a1a/888?text=V8", url_570xN: "https://placehold.co/570x456/1a1a1a/888?text=Color+Options", url_fullxfull: "https://placehold.co/1200/1a1a1a/888?text=Color+Options", alt_text: "", rank: 8 },
    ],
    created_timestamp: 1700000000,
    updated_timestamp: 1706000000,
  },
  {
    listing_id: 1002,
    title: "Wooden Candle Holder Set",
    description: "Set of 3 wooden candle holders. Handmade from reclaimed oak.",
    tags: ["candle holder", "wooden decor", "rustic", "oak", "reclaimed wood"],
    price: { amount: 3200, divisor: 100, currency_code: "USD" },
    quantity: 8,
    taxonomy_id: 6648,
    materials: ["reclaimed oak"],
    shipping_profile_id: 102,
    processing_min: 5,
    processing_max: 7,
    who_made: "i_did",
    when_made: "2020_2025",
    styles: ["Rustic"],
    is_personalizable: true,
    personalization_char_count_max: 30,
    personalization_instructions: "Add custom engraving text (up to 30 characters)",
    views: 342,
    state: "active",
    url: "https://www.etsy.com/listing/1002/wooden-candle-holder-set",
    shop_section_id: 202,
    images: [
      { listing_image_id: 5010, listing_id: 1002, url_75x75: "https://placehold.co/75/1a1a1a/888?text=CH", url_170x135: "https://placehold.co/170x135/1a1a1a/888?text=Candle", url_570xN: "https://placehold.co/570x456/1a1a1a/888?text=Candle+Holder", url_fullxfull: "https://placehold.co/1200/1a1a1a/888?text=Candle+Holder", alt_text: "", rank: 1 },
      { listing_image_id: 5011, listing_id: 1002, url_75x75: "https://placehold.co/75/1a1a1a/888?text=CH2", url_170x135: "https://placehold.co/170x135/1a1a1a/888?text=CH2", url_570xN: "https://placehold.co/570x456/1a1a1a/888?text=Set+of+3", url_fullxfull: "https://placehold.co/1200/1a1a1a/888?text=Set+of+3", alt_text: "", rank: 2 },
      { listing_image_id: 5012, listing_id: 1002, url_75x75: "https://placehold.co/75/1a1a1a/888?text=CH3", url_170x135: "https://placehold.co/170x135/1a1a1a/888?text=CH3", url_570xN: "https://placehold.co/570x456/1a1a1a/888?text=Detail", url_fullxfull: "https://placehold.co/1200/1a1a1a/888?text=Detail", alt_text: "", rank: 3 },
    ],
    created_timestamp: 1702000000,
    updated_timestamp: 1707000000,
  },
  {
    listing_id: 1003,
    title: "Macrame Wall Hanging | Boho Decor | Woven Tapestry | Bohemian Wall Art | Fiber Art | Nursery Decor",
    description: "Stunning macrame wall hanging, handcrafted from 100% natural cotton cord.\n\nThis boho-style woven tapestry adds warmth and texture to any space — perfect for living rooms, bedrooms, or nurseries.\n\nDimensions:\n- Width: 24 inches (including dowel)\n- Length: 36 inches\n\nMaterials: 100% unbleached cotton cord, natural wood dowel\n\nEach piece is made to order. Slight variations make every piece unique.\n\nShipping: Ready to ship in 5-7 business days.",
    tags: [
      "macrame wall hanging", "boho decor", "woven tapestry", "bohemian wall art",
      "fiber art", "nursery decor", "cotton macrame", "handmade wall hanging",
      "boho nursery", "woven wall art", "macrame tapestry", "natural decor", "textile art"
    ],
    price: { amount: 7800, divisor: 100, currency_code: "USD" },
    quantity: 5,
    taxonomy_id: 6650,
    materials: ["cotton cord", "wood dowel"],
    shipping_profile_id: 103,
    processing_min: 5,
    processing_max: 7,
    who_made: "i_did",
    when_made: "2020_2025",
    styles: ["Bohemian", "Boho"],
    is_personalizable: false,
    personalization_char_count_max: 0,
    personalization_instructions: "",
    views: 2156,
    state: "active",
    url: "https://www.etsy.com/listing/1003/macrame-wall-hanging",
    shop_section_id: 203,
    images: [
      { listing_image_id: 5020, listing_id: 1003, url_75x75: "https://placehold.co/75/1a1a1a/888?text=MW", url_170x135: "https://placehold.co/170x135/1a1a1a/888?text=Macrame", url_570xN: "https://placehold.co/570x456/1a1a1a/888?text=Macrame+Hanging", url_fullxfull: "https://placehold.co/1200/1a1a1a/888?text=Macrame+Hanging", alt_text: "Large macrame wall hanging in boho living room", rank: 1 },
      { listing_image_id: 5021, listing_id: 1003, url_75x75: "https://placehold.co/75/1a1a1a/888?text=MW2", url_170x135: "https://placehold.co/170x135/1a1a1a/888?text=MW2", url_570xN: "https://placehold.co/570x456/1a1a1a/888?text=Close+Up", url_fullxfull: "https://placehold.co/1200/1a1a1a/888?text=Close+Up", alt_text: "Detailed view of cotton macrame knots and patterns", rank: 2 },
      { listing_image_id: 5022, listing_id: 1003, url_75x75: "https://placehold.co/75/1a1a1a/888?text=MW3", url_170x135: "https://placehold.co/170x135/1a1a1a/888?text=MW3", url_570xN: "https://placehold.co/570x456/1a1a1a/888?text=Nursery", url_fullxfull: "https://placehold.co/1200/1a1a1a/888?text=Nursery", alt_text: "Macrame wall art in neutral nursery decor", rank: 3 },
      { listing_image_id: 5023, listing_id: 1003, url_75x75: "https://placehold.co/75/1a1a1a/888?text=MW4", url_170x135: "https://placehold.co/170x135/1a1a1a/888?text=MW4", url_570xN: "https://placehold.co/570x456/1a1a1a/888?text=Scale", url_fullxfull: "https://placehold.co/1200/1a1a1a/888?text=Scale", alt_text: "", rank: 4 },
      { listing_image_id: 5024, listing_id: 1003, url_75x75: "https://placehold.co/75/1a1a1a/888?text=MW5", url_170x135: "https://placehold.co/170x135/1a1a1a/888?text=MW5", url_570xN: "https://placehold.co/570x456/1a1a1a/888?text=Bedroom", url_fullxfull: "https://placehold.co/1200/1a1a1a/888?text=Bedroom", alt_text: "Bohemian woven tapestry above bed headboard", rank: 5 },
      { listing_image_id: 5025, listing_id: 1003, url_75x75: "https://placehold.co/75/1a1a1a/888?text=MW6", url_170x135: "https://placehold.co/170x135/1a1a1a/888?text=MW6", url_570xN: "https://placehold.co/570x456/1a1a1a/888?text=Materials", url_fullxfull: "https://placehold.co/1200/1a1a1a/888?text=Materials", alt_text: "", rank: 6 },
    ],
    created_timestamp: 1698000000,
    updated_timestamp: 1705000000,
  },
  {
    listing_id: 1004,
    title: "Scented Soy Candle",
    description: "Hand-poured soy candle. Lavender scent.",
    tags: ["soy candle", "lavender", "scented candle"],
    price: { amount: 1800, divisor: 100, currency_code: "USD" },
    quantity: 25,
    taxonomy_id: 6651,
    materials: [],
    shipping_profile_id: 104,
    processing_min: 0,
    processing_max: 0,
    who_made: "i_did",
    when_made: "2020_2025",
    styles: [],
    is_personalizable: false,
    personalization_char_count_max: 0,
    personalization_instructions: "",
    views: 89,
    state: "active",
    url: "https://www.etsy.com/listing/1004/scented-soy-candle",
    shop_section_id: 0,
    images: [
      { listing_image_id: 5030, listing_id: 1004, url_75x75: "https://placehold.co/75/1a1a1a/888?text=SC", url_170x135: "https://placehold.co/170x135/1a1a1a/888?text=Candle", url_570xN: "https://placehold.co/570x456/1a1a1a/888?text=Soy+Candle", url_fullxfull: "https://placehold.co/1200/1a1a1a/888?text=Soy+Candle", alt_text: "", rank: 1 },
      { listing_image_id: 5031, listing_id: 1004, url_75x75: "https://placehold.co/75/1a1a1a/888?text=SC2", url_170x135: "https://placehold.co/170x135/1a1a1a/888?text=SC2", url_570xN: "https://placehold.co/570x456/1a1a1a/888?text=Lit", url_fullxfull: "https://placehold.co/1200/1a1a1a/888?text=Lit", alt_text: "", rank: 2 },
    ],
    created_timestamp: 1705000000,
    updated_timestamp: 1707500000,
  },
  {
    listing_id: 1005,
    title: "Linen Table Runner | Natural Linen Tablecloth | Farmhouse Table Decor | Wedding Table Runner",
    description: "Elegant linen table runner made from premium European flax linen.\n\nPerfect for everyday dining or special occasions like weddings and holiday gatherings.\n\nAvailable sizes:\n- 14\" x 72\" (standard)\n- 14\" x 90\" (long)\n- 14\" x 108\" (extra long)\n\nMaterials: 100% European flax linen, pre-washed for softness\n\nCare: Machine washable, tumble dry low. Gets softer with each wash.\n\nNote: Color may vary slightly due to monitor settings.",
    tags: [
      "linen table runner", "farmhouse decor", "wedding table runner", "natural linen",
      "table decor", "dining table runner", "european linen", "rustic table setting",
      "holiday table decor", "linen tablecloth", "wedding centerpiece"
    ],
    price: { amount: 3400, divisor: 100, currency_code: "USD" },
    quantity: 18,
    taxonomy_id: 6655,
    materials: ["european flax linen"],
    shipping_profile_id: 105,
    processing_min: 2,
    processing_max: 4,
    who_made: "i_did",
    when_made: "2020_2025",
    styles: ["Farmhouse", "Rustic"],
    is_personalizable: true,
    personalization_char_count_max: 50,
    personalization_instructions: "Add monogram or custom text (up to 50 characters)",
    views: 876,
    state: "active",
    url: "https://www.etsy.com/listing/1005/linen-table-runner",
    shop_section_id: 204,
    images: [
      { listing_image_id: 5040, listing_id: 1005, url_75x75: "https://placehold.co/75/1a1a1a/888?text=TR", url_170x135: "https://placehold.co/170x135/1a1a1a/888?text=Runner", url_570xN: "https://placehold.co/570x456/1a1a1a/888?text=Table+Runner", url_fullxfull: "https://placehold.co/1200/1a1a1a/888?text=Table+Runner", alt_text: "Natural linen table runner on farmhouse dining table", rank: 1 },
      { listing_image_id: 5041, listing_id: 1005, url_75x75: "https://placehold.co/75/1a1a1a/888?text=TR2", url_170x135: "https://placehold.co/170x135/1a1a1a/888?text=TR2", url_570xN: "https://placehold.co/570x456/1a1a1a/888?text=Texture", url_fullxfull: "https://placehold.co/1200/1a1a1a/888?text=Texture", alt_text: "Close-up of premium European flax linen weave", rank: 2 },
      { listing_image_id: 5042, listing_id: 1005, url_75x75: "https://placehold.co/75/1a1a1a/888?text=TR3", url_170x135: "https://placehold.co/170x135/1a1a1a/888?text=TR3", url_570xN: "https://placehold.co/570x456/1a1a1a/888?text=Wedding", url_fullxfull: "https://placehold.co/1200/1a1a1a/888?text=Wedding", alt_text: "Linen runner styled for wedding reception table", rank: 3 },
      { listing_image_id: 5043, listing_id: 1005, url_75x75: "https://placehold.co/75/1a1a1a/888?text=TR4", url_170x135: "https://placehold.co/170x135/1a1a1a/888?text=TR4", url_570xN: "https://placehold.co/570x456/1a1a1a/888?text=Folded", url_fullxfull: "https://placehold.co/1200/1a1a1a/888?text=Folded", alt_text: "", rank: 4 },
      { listing_image_id: 5044, listing_id: 1005, url_75x75: "https://placehold.co/75/1a1a1a/888?text=TR5", url_170x135: "https://placehold.co/170x135/1a1a1a/888?text=TR5", url_570xN: "https://placehold.co/570x456/1a1a1a/888?text=Colors", url_fullxfull: "https://placehold.co/1200/1a1a1a/888?text=Colors", alt_text: "", rank: 5 },
      { listing_image_id: 5045, listing_id: 1005, url_75x75: "https://placehold.co/75/1a1a1a/888?text=TR6", url_170x135: "https://placehold.co/170x135/1a1a1a/888?text=TR6", url_570xN: "https://placehold.co/570x456/1a1a1a/888?text=Holiday", url_fullxfull: "https://placehold.co/1200/1a1a1a/888?text=Holiday", alt_text: "Linen table runner with holiday centerpiece arrangement", rank: 6 },
      { listing_image_id: 5046, listing_id: 1005, url_75x75: "https://placehold.co/75/1a1a1a/888?text=TR7", url_170x135: "https://placehold.co/170x135/1a1a1a/888?text=TR7", url_570xN: "https://placehold.co/570x456/1a1a1a/888?text=Packaging", url_fullxfull: "https://placehold.co/1200/1a1a1a/888?text=Packaging", alt_text: "", rank: 7 },
    ],
    created_timestamp: 1701000000,
    updated_timestamp: 1706500000,
  },
  {
    listing_id: 1006,
    title: "Woven Storage Basket | Seagrass Basket | Boho Planter Cover | Laundry Basket | Home Organization",
    description: "Handwoven seagrass storage basket — versatile and beautiful.\n\nUse as a planter cover, laundry basket, toy storage, or decorative accent.\n\nAvailable sizes:\n- Small: 8\" x 8\"\n- Medium: 10\" x 10\"\n- Large: 12\" x 14\"\n\nMaterials: Natural seagrass, hand-woven by skilled artisans.\n\nCare: Wipe clean with damp cloth. Keep away from excessive moisture.\n\nShipping: Ships in 3-5 business days.",
    tags: [
      "seagrass basket", "woven basket", "boho planter", "storage basket",
      "laundry basket", "home organization", "decorative basket", "plant basket",
      "boho home decor", "toy storage", "woven planter", "natural basket", "handwoven basket"
    ],
    price: { amount: 2900, divisor: 100, currency_code: "USD" },
    quantity: 20,
    taxonomy_id: 6648,
    materials: ["natural seagrass"],
    shipping_profile_id: 106,
    processing_min: 3,
    processing_max: 5,
    who_made: "someone_else",
    when_made: "2020_2025",
    styles: ["Bohemian", "Natural"],
    is_personalizable: false,
    personalization_char_count_max: 0,
    personalization_instructions: "",
    views: 1584,
    state: "active",
    url: "https://www.etsy.com/listing/1006/woven-storage-basket",
    shop_section_id: 205,
    images: [
      { listing_image_id: 5050, listing_id: 1006, url_75x75: "https://placehold.co/75/1a1a1a/888?text=SB", url_170x135: "https://placehold.co/170x135/1a1a1a/888?text=Basket", url_570xN: "https://placehold.co/570x456/1a1a1a/888?text=Seagrass+Basket", url_fullxfull: "https://placehold.co/1200/1a1a1a/888?text=Seagrass+Basket", alt_text: "Handwoven seagrass storage basket in boho room", rank: 1 },
      { listing_image_id: 5051, listing_id: 1006, url_75x75: "https://placehold.co/75/1a1a1a/888?text=SB2", url_170x135: "https://placehold.co/170x135/1a1a1a/888?text=SB2", url_570xN: "https://placehold.co/570x456/1a1a1a/888?text=With+Plant", url_fullxfull: "https://placehold.co/1200/1a1a1a/888?text=With+Plant", alt_text: "Woven basket used as boho planter cover", rank: 2 },
      { listing_image_id: 5052, listing_id: 1006, url_75x75: "https://placehold.co/75/1a1a1a/888?text=SB3", url_170x135: "https://placehold.co/170x135/1a1a1a/888?text=SB3", url_570xN: "https://placehold.co/570x456/1a1a1a/888?text=All+Sizes", url_fullxfull: "https://placehold.co/1200/1a1a1a/888?text=All+Sizes", alt_text: "Three sizes of seagrass baskets side by side", rank: 3 },
      { listing_image_id: 5053, listing_id: 1006, url_75x75: "https://placehold.co/75/1a1a1a/888?text=SB4", url_170x135: "https://placehold.co/170x135/1a1a1a/888?text=SB4", url_570xN: "https://placehold.co/570x456/1a1a1a/888?text=Laundry", url_fullxfull: "https://placehold.co/1200/1a1a1a/888?text=Laundry", alt_text: "", rank: 4 },
      { listing_image_id: 5054, listing_id: 1006, url_75x75: "https://placehold.co/75/1a1a1a/888?text=SB5", url_170x135: "https://placehold.co/170x135/1a1a1a/888?text=SB5", url_570xN: "https://placehold.co/570x456/1a1a1a/888?text=Texture", url_fullxfull: "https://placehold.co/1200/1a1a1a/888?text=Texture", alt_text: "Close-up of natural seagrass weave pattern", rank: 5 },
    ],
    created_timestamp: 1699000000,
    updated_timestamp: 1706000000,
  },
  {
    listing_id: 1007,
    title: "Custom wood sign",
    description: "Custom sign. Contact me for details.",
    tags: ["sign", "wood", "custom"],
    price: { amount: 5500, divisor: 100, currency_code: "USD" },
    quantity: 3,
    taxonomy_id: 0,
    materials: [],
    shipping_profile_id: 107,
    processing_min: 0,
    processing_max: 0,
    who_made: "i_did",
    when_made: "2020_2025",
    styles: [],
    is_personalizable: false,
    personalization_char_count_max: 0,
    personalization_instructions: "",
    views: 24,
    state: "active",
    url: "https://www.etsy.com/listing/1007/custom-wood-sign",
    shop_section_id: 0,
    images: [
      { listing_image_id: 5060, listing_id: 1007, url_75x75: "https://placehold.co/75/1a1a1a/888?text=WS", url_170x135: "https://placehold.co/170x135/1a1a1a/888?text=Sign", url_570xN: "https://placehold.co/570x456/1a1a1a/888?text=Wood+Sign", url_fullxfull: "https://placehold.co/1200/1a1a1a/888?text=Wood+Sign", alt_text: "", rank: 1 },
    ],
    created_timestamp: 1706000000,
    updated_timestamp: 1707000000,
  },
];

// --- Mock AI Recommendations ---

export function getMockRecommendations(listingId: number): AIRecommendations {
  const listing = MOCK_LISTINGS.find((l) => l.listing_id === listingId) ?? MOCK_LISTINGS[0];
  if (!listing) {
    throw new Error("No mock listings available");
  }

  return {
    title: {
      current: listing.title,
      recommended: `${listing.title}${listing.title.length < 80 ? " | Handmade Home Decor | Perfect Gift | Free Shipping" : ""}`,
      reasoning: "Front-load primary keywords. Use pipe separators for readability. Include gift-related terms to capture gift shoppers. Aim for 80-140 characters to maximize keyword coverage.",
    },
    tags: {
      current: listing.tags,
      recommended: listing.tags.length >= 13
        ? listing.tags
        : [
            ...listing.tags,
            "home decor gift",
            "housewarming gift",
            "unique home accent",
            "handcrafted decor",
            "artisan home goods",
            "modern farmhouse",
            "gift for her",
            "interior design",
            "home styling",
            "aesthetic decor",
          ].slice(0, 13),
      reasoning: "Fill all 13 tag slots. Mix broad terms (home decor) with long-tail phrases (handcrafted home accent). Include gift-related tags to capture seasonal shoppers.",
    },
    description: {
      current: listing.description.slice(0, 200),
      recommended: listing.description.length > 300
        ? listing.description
        : `${listing.description}\n\nThis piece makes a thoughtful gift for housewarmings, birthdays, or holidays. Each item is carefully crafted and inspected for quality.\n\nWhy shop with us?\n- Handmade with premium materials\n- Eco-friendly packaging\n- Fast processing & careful shipping\n- 100% satisfaction guaranteed\n\nHave questions? Message us anytime — we're happy to help!`,
      reasoning: "Expand description to 500+ characters. Include keywords naturally. Add trust signals (satisfaction guarantee, quality inspection). Include a call to action.",
    },
    altTexts: listing.images
      .filter((img) => !img.alt_text || img.alt_text.length < 20)
      .slice(0, 3)
      .map((img, i) => ({
        imageIndex: img.rank - 1,
        current: img.alt_text || "",
        recommended: `${listing.title.split("|")[0].trim()} - ${["front view product photo", "detailed texture close-up", "styled in home setting"][i % 3]}`,
      })),
    category: {
      current: listing.taxonomy_id || null,
      recommended: listing.taxonomy_id
        ? `Category ID ${listing.taxonomy_id} appears to match what top competitors use for similar products. No change needed.`
        : "Set a category for this listing. Most competitors in this niche use category IDs in the 6648-6655 range (Home & Living > Home Decor). Choose the most specific subcategory that fits your product.",
      reasoning: listing.taxonomy_id
        ? "Your category matches the majority of top-ranking competitors."
        : "Missing category hurts discoverability — Etsy uses taxonomy to surface listings in browse and search.",
    },
    overallStrategy: `Focus on filling all 13 tags, expanding the description with keywords and trust signals, and adding descriptive alt text to all ${listing.images.filter((img) => !img.alt_text).length} images missing it.`,
  };
}

// --- Mock Keyword Research ---

export const MOCK_KEYWORD_RESULT: KeywordResearchResult = {
  seedKeyword: "home decor",
  autocompleteSuggestions: [
    "home decor aesthetic",
    "home decor boho",
    "home decor farmhouse",
    "home decor minimalist",
    "home decor living room",
    "home decor modern",
    "home decor vintage",
    "home decor wall art",
    "home decor candle",
    "home decor gift",
  ],
  competitors: [
    { listing_id: 9001, title: "Boho Wall Art Print Set | Home Decor | Living Room Gallery Wall", tags: ["boho wall art", "home decor", "gallery wall", "living room art", "boho prints"], taxonomy_id: 6648, views: 4532, url: "https://etsy.com/listing/9001", price: 28.99 },
    { listing_id: 9002, title: "Handmade Ceramic Planter | Indoor Plant Pot | Modern Home Decor", tags: ["ceramic planter", "indoor planter", "home decor", "plant pot", "modern planter"], taxonomy_id: 6648, views: 3210, url: "https://etsy.com/listing/9002", price: 34.50 },
    { listing_id: 9003, title: "Macrame Plant Hanger | Boho Home Decor | Hanging Planter | Cotton Rope", tags: ["macrame hanger", "plant hanger", "boho decor", "hanging planter", "cotton macrame"], taxonomy_id: 6650, views: 5678, url: "https://etsy.com/listing/9003", price: 22.00 },
    { listing_id: 9004, title: "Wooden Floating Shelves Set of 3 | Rustic Wall Shelves | Farmhouse Decor", tags: ["floating shelves", "wall shelves", "rustic decor", "farmhouse", "wood shelves"], taxonomy_id: 6648, views: 2890, url: "https://etsy.com/listing/9004", price: 45.99 },
    { listing_id: 9005, title: "Soy Candle Gift Set | Home Decor Candles | Aromatherapy | Self Care Gift", tags: ["soy candle", "candle gift set", "aromatherapy", "self care", "home decor candle"], taxonomy_id: 6651, views: 1890, url: "https://etsy.com/listing/9005", price: 32.00 },
  ],
  tagFrequency: [
    { tag: "home decor", count: 15 },
    { tag: "boho decor", count: 12 },
    { tag: "handmade", count: 11 },
    { tag: "wall art", count: 9 },
    { tag: "living room", count: 8 },
    { tag: "farmhouse decor", count: 7 },
    { tag: "gift for her", count: 7 },
    { tag: "modern decor", count: 6 },
    { tag: "rustic decor", count: 6 },
    { tag: "minimalist", count: 5 },
    { tag: "housewarming gift", count: 5 },
    { tag: "boho home", count: 5 },
    { tag: "plant decor", count: 4 },
    { tag: "ceramic", count: 4 },
    { tag: "macrame", count: 4 },
    { tag: "natural materials", count: 3 },
    { tag: "eco friendly", count: 3 },
    { tag: "aesthetic decor", count: 3 },
    { tag: "cozy home", count: 3 },
    { tag: "interior design", count: 2 },
  ],
  titleKeywords: [
    { word: "decor", count: 18 },
    { word: "home", count: 16 },
    { word: "handmade", count: 10 },
    { word: "boho", count: 9 },
    { word: "wall", count: 8 },
    { word: "modern", count: 7 },
    { word: "gift", count: 7 },
    { word: "farmhouse", count: 6 },
    { word: "rustic", count: 5 },
    { word: "ceramic", count: 5 },
    { word: "natural", count: 4 },
    { word: "plant", count: 4 },
    { word: "living", count: 4 },
    { word: "room", count: 4 },
    { word: "wood", count: 3 },
    { word: "art", count: 3 },
  ],
};

// --- Mock AI Keyword Suggestions ---

export const MOCK_AI_SUGGESTIONS = {
  keywords: [
    "bohemian home accents",
    "modern farmhouse decor",
    "handcrafted home goods",
    "artisan home decor",
    "cozy living room decor",
    "natural home accessories",
    "eco-friendly home decor",
    "unique housewarming gift",
    "aesthetic room decor",
    "minimalist home styling",
    "rustic chic decor",
    "organic home accents",
    "handmade gift ideas",
    "interior decorating ideas",
    "neutral home decor",
  ],
  reasoning: "These keywords target a mix of broad discovery terms (home decor, gift ideas) and specific long-tail phrases (bohemian home accents, rustic chic decor) that top competitors are ranking for. Gift-related terms capture seasonal traffic. Style-specific terms (minimalist, farmhouse, boho) help match buyer intent.",
};
